/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendedorRouteImport } from './routes/_authenticated/vendedor'
import { Route as AuthenticatedColaRouteImport } from './routes/_authenticated/cola'
import { Route as AuthenticatedBandejaRouteImport } from './routes/_authenticated/bandeja'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVendedorIndexRouteImport } from './routes/_authenticated/vendedor/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedVendedorProductosRouteImport } from './routes/_authenticated/vendedor/productos'
import { Route as AuthenticatedVendedorPerfilRouteImport } from './routes/_authenticated/vendedor/perfil'
import { Route as AuthenticatedVendedorPedidosRouteImport } from './routes/_authenticated/vendedor/pedidos'
import { Route as AuthenticatedVendedorNuevoRouteImport } from './routes/_authenticated/vendedor/nuevo'
import { Route as AuthenticatedVendedorClientesRouteImport } from './routes/_authenticated/vendedor/clientes'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos/$id'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminSolicitudesRouteImport } from './routes/_authenticated/admin/solicitudes'
import { Route as AuthenticatedAdminSiigoRouteImport } from './routes/_authenticated/admin/siigo'
import { Route as AuthenticatedAdminReportesRouteImport } from './routes/_authenticated/admin/reportes'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated/admin/productos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminMediosPagoRouteImport } from './routes/_authenticated/admin/medios-pago'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin/clientes'
import { Route as AuthenticatedAdminAjustesRouteImport } from './routes/_authenticated/admin/ajustes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendedorRoute = AuthenticatedVendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedColaRoute = AuthenticatedColaRouteImport.update({
  id: '/cola',
  path: '/cola',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBandejaRoute = AuthenticatedBandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendedorIndexRoute =
  AuthenticatedVendedorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedVendedorProductosRoute =
  AuthenticatedVendedorProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorPerfilRoute =
  AuthenticatedVendedorPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorPedidosRoute =
  AuthenticatedVendedorPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorNuevoRoute =
  AuthenticatedVendedorNuevoRouteImport.update({
    id: '/nuevo',
    path: '/nuevo',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorClientesRoute =
  AuthenticatedVendedorClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSolicitudesRoute =
  AuthenticatedAdminSolicitudesRouteImport.update({
    id: '/solicitudes',
    path: '/solicitudes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSiigoRoute = AuthenticatedAdminSiigoRouteImport.update({
  id: '/siigo',
  path: '/siigo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportesRoute =
  AuthenticatedAdminReportesRouteImport.update({
    id: '/reportes',
    path: '/reportes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediosPagoRoute =
  AuthenticatedAdminMediosPagoRouteImport.update({
    id: '/medios-pago',
    path: '/medios-pago',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAjustesRoute =
  AuthenticatedAdminAjustesRouteImport.update({
    id: '/ajustes',
    path: '/ajustes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/bandeja': typeof AuthenticatedBandejaRoute
  '/cola': typeof AuthenticatedColaRoute
  '/vendedor': typeof AuthenticatedVendedorRouteWithChildren
  '/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/medios-pago': typeof AuthenticatedAdminMediosPagoRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/siigo': typeof AuthenticatedAdminSiigoRoute
  '/admin/solicitudes': typeof AuthenticatedAdminSolicitudesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/vendedor/nuevo': typeof AuthenticatedVendedorNuevoRoute
  '/vendedor/pedidos': typeof AuthenticatedVendedorPedidosRoute
  '/vendedor/perfil': typeof AuthenticatedVendedorPerfilRoute
  '/vendedor/productos': typeof AuthenticatedVendedorProductosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/vendedor/': typeof AuthenticatedVendedorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bandeja': typeof AuthenticatedBandejaRoute
  '/cola': typeof AuthenticatedColaRoute
  '/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/medios-pago': typeof AuthenticatedAdminMediosPagoRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/siigo': typeof AuthenticatedAdminSiigoRoute
  '/admin/solicitudes': typeof AuthenticatedAdminSolicitudesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/vendedor/nuevo': typeof AuthenticatedVendedorNuevoRoute
  '/vendedor/pedidos': typeof AuthenticatedVendedorPedidosRoute
  '/vendedor/perfil': typeof AuthenticatedVendedorPerfilRoute
  '/vendedor/productos': typeof AuthenticatedVendedorProductosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/vendedor': typeof AuthenticatedVendedorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/bandeja': typeof AuthenticatedBandejaRoute
  '/_authenticated/cola': typeof AuthenticatedColaRoute
  '/_authenticated/vendedor': typeof AuthenticatedVendedorRouteWithChildren
  '/_authenticated/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/medios-pago': typeof AuthenticatedAdminMediosPagoRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/_authenticated/admin/siigo': typeof AuthenticatedAdminSiigoRoute
  '/_authenticated/admin/solicitudes': typeof AuthenticatedAdminSolicitudesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/_authenticated/vendedor/nuevo': typeof AuthenticatedVendedorNuevoRoute
  '/_authenticated/vendedor/pedidos': typeof AuthenticatedVendedorPedidosRoute
  '/_authenticated/vendedor/perfil': typeof AuthenticatedVendedorPerfilRoute
  '/_authenticated/vendedor/productos': typeof AuthenticatedVendedorProductosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/vendedor/': typeof AuthenticatedVendedorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/bandeja'
    | '/cola'
    | '/vendedor'
    | '/admin/ajustes'
    | '/admin/clientes'
    | '/admin/medios-pago'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/siigo'
    | '/admin/solicitudes'
    | '/admin/usuarios'
    | '/pedidos/$id'
    | '/vendedor/clientes'
    | '/vendedor/nuevo'
    | '/vendedor/pedidos'
    | '/vendedor/perfil'
    | '/vendedor/productos'
    | '/admin/'
    | '/vendedor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/bandeja'
    | '/cola'
    | '/admin/ajustes'
    | '/admin/clientes'
    | '/admin/medios-pago'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/siigo'
    | '/admin/solicitudes'
    | '/admin/usuarios'
    | '/pedidos/$id'
    | '/vendedor/clientes'
    | '/vendedor/nuevo'
    | '/vendedor/pedidos'
    | '/vendedor/perfil'
    | '/vendedor/productos'
    | '/admin'
    | '/vendedor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/bandeja'
    | '/_authenticated/cola'
    | '/_authenticated/vendedor'
    | '/_authenticated/admin/ajustes'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/medios-pago'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/productos'
    | '/_authenticated/admin/reportes'
    | '/_authenticated/admin/siigo'
    | '/_authenticated/admin/solicitudes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/vendedor/clientes'
    | '/_authenticated/vendedor/nuevo'
    | '/_authenticated/vendedor/pedidos'
    | '/_authenticated/vendedor/perfil'
    | '/_authenticated/vendedor/productos'
    | '/_authenticated/admin/'
    | '/_authenticated/vendedor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendedor': {
      id: '/_authenticated/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof AuthenticatedVendedorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cola': {
      id: '/_authenticated/cola'
      path: '/cola'
      fullPath: '/cola'
      preLoaderRoute: typeof AuthenticatedColaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bandeja': {
      id: '/_authenticated/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof AuthenticatedBandejaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendedor/': {
      id: '/_authenticated/vendedor/'
      path: '/'
      fullPath: '/vendedor/'
      preLoaderRoute: typeof AuthenticatedVendedorIndexRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/vendedor/productos': {
      id: '/_authenticated/vendedor/productos'
      path: '/productos'
      fullPath: '/vendedor/productos'
      preLoaderRoute: typeof AuthenticatedVendedorProductosRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/perfil': {
      id: '/_authenticated/vendedor/perfil'
      path: '/perfil'
      fullPath: '/vendedor/perfil'
      preLoaderRoute: typeof AuthenticatedVendedorPerfilRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/pedidos': {
      id: '/_authenticated/vendedor/pedidos'
      path: '/pedidos'
      fullPath: '/vendedor/pedidos'
      preLoaderRoute: typeof AuthenticatedVendedorPedidosRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/nuevo': {
      id: '/_authenticated/vendedor/nuevo'
      path: '/nuevo'
      fullPath: '/vendedor/nuevo'
      preLoaderRoute: typeof AuthenticatedVendedorNuevoRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/clientes': {
      id: '/_authenticated/vendedor/clientes'
      path: '/clientes'
      fullPath: '/vendedor/clientes'
      preLoaderRoute: typeof AuthenticatedVendedorClientesRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/solicitudes': {
      id: '/_authenticated/admin/solicitudes'
      path: '/solicitudes'
      fullPath: '/admin/solicitudes'
      preLoaderRoute: typeof AuthenticatedAdminSolicitudesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/siigo': {
      id: '/_authenticated/admin/siigo'
      path: '/siigo'
      fullPath: '/admin/siigo'
      preLoaderRoute: typeof AuthenticatedAdminSiigoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reportes': {
      id: '/_authenticated/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AuthenticatedAdminReportesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos': {
      id: '/_authenticated/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/medios-pago': {
      id: '/_authenticated/admin/medios-pago'
      path: '/medios-pago'
      fullPath: '/admin/medios-pago'
      preLoaderRoute: typeof AuthenticatedAdminMediosPagoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ajustes': {
      id: '/_authenticated/admin/ajustes'
      path: '/ajustes'
      fullPath: '/admin/ajustes'
      preLoaderRoute: typeof AuthenticatedAdminAjustesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAjustesRoute: typeof AuthenticatedAdminAjustesRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminMediosPagoRoute: typeof AuthenticatedAdminMediosPagoRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminReportesRoute: typeof AuthenticatedAdminReportesRoute
  AuthenticatedAdminSiigoRoute: typeof AuthenticatedAdminSiigoRoute
  AuthenticatedAdminSolicitudesRoute: typeof AuthenticatedAdminSolicitudesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAjustesRoute: AuthenticatedAdminAjustesRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminMediosPagoRoute: AuthenticatedAdminMediosPagoRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
  AuthenticatedAdminReportesRoute: AuthenticatedAdminReportesRoute,
  AuthenticatedAdminSiigoRoute: AuthenticatedAdminSiigoRoute,
  AuthenticatedAdminSolicitudesRoute: AuthenticatedAdminSolicitudesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedVendedorRouteChildren {
  AuthenticatedVendedorClientesRoute: typeof AuthenticatedVendedorClientesRoute
  AuthenticatedVendedorNuevoRoute: typeof AuthenticatedVendedorNuevoRoute
  AuthenticatedVendedorPedidosRoute: typeof AuthenticatedVendedorPedidosRoute
  AuthenticatedVendedorPerfilRoute: typeof AuthenticatedVendedorPerfilRoute
  AuthenticatedVendedorProductosRoute: typeof AuthenticatedVendedorProductosRoute
  AuthenticatedVendedorIndexRoute: typeof AuthenticatedVendedorIndexRoute
}

const AuthenticatedVendedorRouteChildren: AuthenticatedVendedorRouteChildren = {
  AuthenticatedVendedorClientesRoute: AuthenticatedVendedorClientesRoute,
  AuthenticatedVendedorNuevoRoute: AuthenticatedVendedorNuevoRoute,
  AuthenticatedVendedorPedidosRoute: AuthenticatedVendedorPedidosRoute,
  AuthenticatedVendedorPerfilRoute: AuthenticatedVendedorPerfilRoute,
  AuthenticatedVendedorProductosRoute: AuthenticatedVendedorProductosRoute,
  AuthenticatedVendedorIndexRoute: AuthenticatedVendedorIndexRoute,
}

const AuthenticatedVendedorRouteWithChildren =
  AuthenticatedVendedorRoute._addFileChildren(
    AuthenticatedVendedorRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBandejaRoute: typeof AuthenticatedBandejaRoute
  AuthenticatedColaRoute: typeof AuthenticatedColaRoute
  AuthenticatedVendedorRoute: typeof AuthenticatedVendedorRouteWithChildren
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBandejaRoute: AuthenticatedBandejaRoute,
  AuthenticatedColaRoute: AuthenticatedColaRoute,
  AuthenticatedVendedorRoute: AuthenticatedVendedorRouteWithChildren,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
